//---------------------------------------------------------------------------

#ifndef MainUnitH
#define MainUnitH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <UOMAPLib_OCX.h>
#include <OleCtrls.hpp>
#include <ComCtrls.hpp>
#include <Dialogs.hpp>
#include <Registry.hpp>
#include <Sockets.hpp>
#include <ScktComp.hpp>
#include <UOARTLib_OCX.h>
#include "ErrorUnit.h"
#include <Menus.hpp>
//---------------------------------------------------------------------------
class TMainForm : public TForm
{
__published:	// IDE-managed Components
        TPageControl *Pager;
        TTabSheet *TravelTab;
	TTabSheet *s;
	TGroupBox *GroupBox2;
	TButton *GoCmd;
	TGroupBox *GroupBox3;
	TEdit *newy;
	TEdit *newx;
	TButton *VaiBtn;
	TListBox *LocPlaces;
	TEdit *newz;
	TGroupBox *GroupBox1;
	TLabel *Label1;
	TCheckBox *NewLine;
	TEdit *CmdPrefix;
	TGroupBox *GroupBox4;
	TLabel *Label2;
	TCheckBox *AoT;
	TCheckBox *ExitOnClose;
	TTreeView *LocCategory;
	TTabSheet *LauncherTab;
	TGroupBox *GroupBox5;
	TListBox *ClientList;
	TLabel *Label3;
	TEdit *EntryName;
	TLabel *Label4;
	TEdit *ServerIP;
	TLabel *Label5;
	TEdit *ServerPort;
	TLabel *Label6;
	TEdit *AccountName;
	TLabel *Label7;
	TEdit *AccountPassword;
	TLabel *Label8;
	TEdit *ClientPath;
	TButton *BrowseClient;
	TButton *EditBtn;
	TButton *OKBtn;
	TButton *CancelBtn;
	TButton *AddBtn;
	TButton *RemoveBtn;
	TOpenDialog *ClientDialog;
	TGroupBox *GroupBox6;
	TEdit *DefaultClient;
	TButton *BrowseDefClientBtn;
	TButton *LaunchBtn;
	TCheckBox *Use0x;
	TTabSheet *MiscCmdPage;
	TListBox *FileList;
	TLabel *Label9;
	TButton *AddFileBtn;
	TButton *RemoveFileBtn;
	TGroupBox *GroupBox7;
	TButton *RemoveCmd;
	TButton *SendCmd;
	TButton *SetMOREXYZCmd;
	TGroupBox *GroupBox8;
	TButton *Button1;
	TButton *InvulCmd;
	TButton *NoInvulCmd;
	TButton *HideCmd;
	TButton *UnHideCmd;
	TButton *MakeGMCmd;
	TButton *MakeCNSCmd;
	TTabSheet *CustomCmdsTab;
	TGroupBox *GroupBox9;
	TLabel *Label10;
	TEdit *CmdTitle;
	TLabel *Label11;
	TEdit *DynamicCmd;
	TButton *AddDynCmd;
	TUOMap *Mappa;
	TTabSheet *ItemTab;
	TTabSheet *SpawnTabs;
	TTreeView *ItmCategories;
	TTreeView *ChrCategories;
	TListBox *ItmList;
	TListBox *ChrList;
	TGroupBox *GroupBox12;
	TButton *LoadXSSBtn;
	TOpenDialog *OpenScript;
	TLabel *Label15;
	TButton *AddItemCmd;
	TEdit *itemid;
	TButton *AddCharCmd;
	TLabel *Label16;
	TEdit *charid;
	TLabel *Label17;
	TEdit *NXWPath;
	TButton *BrowseNoxWizardBtn;
	TTabSheet *ThanksTab;
	TMemo *ThanksMemo;
	TGroupBox *GroupBox13;
	TCheckBox *ShowArt;
	TUOArt *ItmArt;
	TGroupBox *GroupBox14;
	TUOArt *ChrArt;
	TCheckBox *Show3DRoom;
	TButton *RemoveCmd2;
	TButton *RemoveCmd3;
	TGroupBox *GroupBox15;
	TEdit *NudgeDelta;
	TUpDown *NudgeControl;
	TGroupBox *GroupBox16;
	TButton *DryCmd;
	TButton *RainCmd;
	TButton *SnowCmd;
	TComboBox *Seasons;
	TButton *SetSeasonCmd;
	TGroupBox *GroupBox17;
	TButton *WholistCmd;
	TButton *OfflistCmd;
	TButton *PlayerListCmd;
	TButton *FreezeCmd;
	TButton *UnfreezeCmd;
	TTabSheet *TweakTab;
	TEdit *Value;
	TLabel *Label18;
	TGroupBox *GroupBox18;
	TGroupBox *GroupBox19;
	TGroupBox *GroupBox20;
	TButton *SetAmountCmd;
	TButton *SetMoreXCmd;
	TButton *SetMoreYCmd;
	TButton *SetMoreZCmd;
	TButton *SetMoreXYZCmd2;
	TButton *SetTypeCmd;
	TButton *SetMoreCmd;
	TButton *SetNPCAICmd;
	TButton *SetFontCmd;
	TButton *ColorPaletteBtn;
	TButton *SetSTRBtn;
	TButton *SetINTBtn;
	TButton *SetDEXBtn;
	TButton *SetHPBtn;
	TButton *SetStaminaBtn;
	TButton *SetManaBtn;
	TComboBox *SkillList;
	TButton *SetSkillBtn;
	TButton *KillCmd;
	TButton *ResurrectCmd;
	TButton *RefreshCmd;
	TButton *ZeroKillsCmd;
	TButton *JailCmd;
	TButton *ReleaseCmd;
	TButton *ShowIDsCmd;
	TButton *BankCmd;
	TButton *SBankCmd;
	TButton *SetXCmd;
	TButton *SetYCmd;
	TButton *SetZCmd;
	TButton *DupeCmd;
	TButton *EclipseCmd;
	TButton *AllMoveOnCmd;
	TButton *AllMoveOffCmd;
	TGroupBox *Regione;
	TButton *GuardsOnCmd;
	TButton *GuardsOffCmd;
	TButton *AnnounceOnCmd;
	TButton *AnnounceOffCmd;
	TButton *GMsCmd;
	TButton *ShowPriv3Cmd;
	TLabel *Label19;
	TButton *DisconnectCmd;
	TButton *KickCmd;
	TButton *InvulCmd2;
	TButton *NoInvulCmd2;
	TButton *HideCmd2;
	TButton *UnHideCmd2;
	TButton *FreezeCmd2;
	TButton *UnFreezeCmd2;
	TButton *KillCmd2;
	TButton *ResurrectCmd2;
	TButton *DupeCmd2;
	TGroupBox *GroupBox21;
	TButton *SaveCmd;
	TButton *PdumpCmd;
	TButton *ReloadScriptCmd;
	TButton *ReloadServerCmd;
	TPopupMenu *PlacesPopup;
	TMenuItem *Modifica1;
	TMenuItem *Inserisci1;
	TPopupMenu *ItemsPopup;
	TMenuItem *MenuItem1;
	TMenuItem *MenuItem2;
	TPopupMenu *CharsPopup;
	TMenuItem *MenuItem3;
	TMenuItem *MenuItem4;
	TMenuItem *Elimina1;
	TMenuItem *Elimina2;
	TMenuItem *Elimina3;
	TOpenDialog *OpenNoxWizard;
	TCheckBox *NoX73Comp;
	TButton *SetHexMoreXY;
	TButton *AddParams;
	TCheckBox *HotKeys;
        void __fastcall MappaMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
	void __fastcall GoCmdClick(TObject *Sender);
	void __fastcall TravelTabShow(TObject *Sender);
	void __fastcall VaiBtnClick(TObject *Sender);
	void __fastcall LocCategoryChange(TObject *Sender, TTreeNode *Node);
	void __fastcall LocPlacesClick(TObject *Sender);
	void __fastcall AoTClick(TObject *Sender);
	void __fastcall ExitOnCloseClick(TObject *Sender);
	void __fastcall Label2Click(TObject *Sender);
	void __fastcall FormCloseQuery(TObject *Sender, bool &CanClose);
	void __fastcall ClientListClick(TObject *Sender);
	void __fastcall EditBtnClick(TObject *Sender);
	void __fastcall CancelBtnClick(TObject *Sender);
	void __fastcall OKBtnClick(TObject *Sender);
	void __fastcall BrowseClientClick(TObject *Sender);
	void __fastcall RemoveBtnClick(TObject *Sender);
	void __fastcall BrowseDefClientBtnClick(TObject *Sender);
	void __fastcall AddBtnClick(TObject *Sender);
	void __fastcall LaunchBtnClick(TObject *Sender);
	void __fastcall Use0xClick(TObject *Sender);
	void __fastcall NewLineClick(TObject *Sender);
	void __fastcall CmdPrefixChange(TObject *Sender);
	void __fastcall RemoveCmdClick(TObject *Sender);
	void __fastcall AddFileBtnClick(TObject *Sender);
	void __fastcall RemoveFileBtnClick(TObject *Sender);
	void __fastcall SendCmdClick(TObject *Sender);
	void __fastcall SetMOREXYZCmdClick(TObject *Sender);
	void __fastcall InvulCmdClick(TObject *Sender);
	void __fastcall NoInvulCmdClick(TObject *Sender);
	void __fastcall HideCmdClick(TObject *Sender);
	void __fastcall UnHideCmdClick(TObject *Sender);
	void __fastcall MakeGMCmdClick(TObject *Sender);
	void __fastcall MakeCNSCmdClick(TObject *Sender);
	void __fastcall AddDynCmdClick(TObject *Sender);
	void __fastcall DynButtonClick(TObject *Sender);
	void __fastcall DynButtonMouseDown(TObject *Sender, TMouseButton Button,
          TShiftState Shift, int X, int Y);
	void __fastcall ItmCategoriesChange(TObject *Sender, TTreeNode *Node);
	void __fastcall ChrCategoriesChange(TObject *Sender, TTreeNode *Node);
	void __fastcall LoadXSSBtnClick(TObject *Sender);
	void __fastcall ItmListClick(TObject *Sender);
	void __fastcall AddItemCmdClick(TObject *Sender);
	void __fastcall ChrListClick(TObject *Sender);
	void __fastcall BrowseNoxWizardBtnClick(TObject *Sender);
	void __fastcall ShowArtClick(TObject *Sender);
	void __fastcall AddCharCmdClick(TObject *Sender);
	void __fastcall Show3DRoomClick(TObject *Sender);
	void __fastcall NudgeControlClick(TObject *Sender, TUDBtnType Button);
	void __fastcall DryCmdClick(TObject *Sender);
	void __fastcall SnowCmdClick(TObject *Sender);
	void __fastcall RainCmdClick(TObject *Sender);
	void __fastcall SetSeasonCmdClick(TObject *Sender);
	void __fastcall EclipseCmdClick(TObject *Sender);
	void __fastcall WholistCmdClick(TObject *Sender);
	void __fastcall PlayerListCmdClick(TObject *Sender);
	void __fastcall OfflistCmdClick(TObject *Sender);
	void __fastcall FreezeCmdClick(TObject *Sender);
	void __fastcall UnfreezeCmdClick(TObject *Sender);
	void __fastcall SetAmountCmdClick(TObject *Sender);
	void __fastcall SetMoreXCmdClick(TObject *Sender);
	void __fastcall SetMoreYCmdClick(TObject *Sender);
	void __fastcall SetMoreZCmdClick(TObject *Sender);
	void __fastcall SetMoreXYZCmd2Click(TObject *Sender);
	void __fastcall SetHexMoreXYZCmdClick(TObject *Sender);
	void __fastcall SetTypeCmdClick(TObject *Sender);
	void __fastcall SetMoreCmdClick(TObject *Sender);
	void __fastcall SetNPCAICmdClick(TObject *Sender);
	void __fastcall SetFontCmdClick(TObject *Sender);
	void __fastcall ColorPaletteBtnClick(TObject *Sender);
	void __fastcall FormShow(TObject *Sender);
	void __fastcall KillCmdClick(TObject *Sender);
	void __fastcall ResurrectCmdClick(TObject *Sender);
	void __fastcall RefreshCmdClick(TObject *Sender);
	void __fastcall SetSkillBtnClick(TObject *Sender);
	void __fastcall SetSTRBtnClick(TObject *Sender);
	void __fastcall SetINTBtnClick(TObject *Sender);
	void __fastcall SetDEXBtnClick(TObject *Sender);
	void __fastcall SetStaminaBtnClick(TObject *Sender);
	void __fastcall SetManaBtnClick(TObject *Sender);
	void __fastcall ZeroKillsCmdClick(TObject *Sender);
	void __fastcall JailCmdClick(TObject *Sender);
	void __fastcall ReleaseCmdClick(TObject *Sender);
	void __fastcall ShowIDsCmdClick(TObject *Sender);
	void __fastcall BankCmdClick(TObject *Sender);
	void __fastcall SBankCmdClick(TObject *Sender);
	void __fastcall SetXCmdClick(TObject *Sender);
	void __fastcall SetYCmdClick(TObject *Sender);
	void __fastcall SetZCmdClick(TObject *Sender);
	void __fastcall DupeCmdClick(TObject *Sender);
	void __fastcall SaveCmdClick(TObject *Sender);
	void __fastcall AllMoveOnCmdClick(TObject *Sender);
	void __fastcall AllMoveOffCmdClick(TObject *Sender);
	void __fastcall GuardsOnCmdClick(TObject *Sender);
	void __fastcall GuardsOffCmdClick(TObject *Sender);
	void __fastcall AnnounceOnCmdClick(TObject *Sender);
	void __fastcall AnnounceOffCmdClick(TObject *Sender);
	void __fastcall GMsCmdClick(TObject *Sender);
	void __fastcall PdumpCmdClick(TObject *Sender);
	void __fastcall ReloadScriptCmdClick(TObject *Sender);
	void __fastcall ShowPriv3CmdClick(TObject *Sender);
	void __fastcall DisconnectCmdClick(TObject *Sender);
	void __fastcall KickCmdClick(TObject *Sender);
	void __fastcall ReloadServerCmdClick(TObject *Sender);
	void __fastcall Modifica1Click(TObject *Sender);
	void __fastcall Elimina1Click(TObject *Sender);
	void __fastcall Inserisci1Click(TObject *Sender);
	void __fastcall Elimina2Click(TObject *Sender);
	void __fastcall Elimina3Click(TObject *Sender);
	void __fastcall MenuItem2Click(TObject *Sender);
	void __fastcall MenuItem4Click(TObject *Sender);
	void __fastcall MenuItem1Click(TObject *Sender);
	void __fastcall MenuItem3Click(TObject *Sender);
	void __fastcall NoX73CompClick(TObject *Sender);
	void __fastcall AddParamsClick(TObject *Sender);
private:	// User declarations
        HWND UOHandle;
        void ReloadClients();
public:		// User declarations
        AnsiString uopath;
        TButton *DynButtons[48];
        int HowManyDyns;

        bool FindUO();
        void SendCommand(AnsiString cmd);
        __fastcall TMainForm(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TMainForm *MainForm;
//---------------------------------------------------------------------------
#endif
